# This workflow is responsible for deploying the application to the production environment.

name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Checkout Infrastructure repo
      uses: actions/checkout@v4
      with:
        repository: njdimmer/task_manager_infrastructure
        token: ${{ secrets.TASK_MANAGER_INFRASTRUCTURE_TOKEN }}
        path: infrastructure

    - name: Create .env file
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./infrastructure/docker/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./infrastructure/docker/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./infrastructure/docker/.env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./infrastructure/docker/.env

    # - name: Install Docker Compose
    #   run: |
    #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #     sudo chmod +x /usr/local/bin/docker-compose
    #     sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    # - name: Copy requirements.txt to infrastructure directory
    #   run: |
    #     cp requirements.txt ./infrastructure/docker/requirements.txt

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/taskmanager:latest -f .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/taskmanager:latest

    # - name: Build and start Docker Compose services
    #   run: |
    #     docker-compose -f infrastructure/docker/docker-compose.yml up --build -d

    # - name: Stop and remove Docker containers
    #   run: |
    #     docker-compose -f infrastructure/docker/docker-compose.yml down