name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [ "completed" ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout Infrastructure repo
      uses: actions/checkout@v4
      with:
        repository: njdimmer/task_manager_infrastructure
        token: ${{ secrets.TASK_MANAGER_INFRASTRUCTURE_TOKEN }}
        path: infrastructure

    - name: Check infra directory contents
      run: |
        ls -la infrastructure

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Build and start Docker Compose services
      run: |
        cd infrastructure
        docker-compose -f docker-compose.yml up --build -d